<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
    <!-- CS8620: OData client library nullability quirks -->
    <NoWarn>$(NoWarn);CS8620</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Kuestenlogik.Surgewave.Connector.Sap.OData.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Kuestenlogik.Surgewave.Connect" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Simple.OData.Client" />
  </ItemGroup>

</Project>
